@startuml
start 
:Load State, and get __projects , teamsOptions, PMsOptions,
 clientsOptions__ **Providing all data needed for filteration**;
:Build component state, from __managers, teams, clients, tasks, journies, allJournies, and State object__;
note right
The State Object contains these data 
*  **filterPopup** : Boolean to show/hide filter menu
*  **filter** : Contains Date interval filter by the journey startedAt date.
*  **data** : Contains the chart **X** labels and its values with **Y** axis
*  **options** : Contains all Chart options that will affect the design of the daigram.
*  **comparisonBy** : Contains the comparison name that should be choosed by the client,
                                 and then controlling the X axis labels and values.
end note
: Set Diagram Data based on filteration and comparison;
note right
* **X axis** : Will split the Time of delivery of journies of on the selected comparison values grouped by the categories.
* **Formula** : The average of TOD by the comparison dataset grouped by categories for each value of the comparison labels.
end note
: global state, or props Changes}
note right
* Any change to the tasks from props,
     will change the tasks info state, and the journies state
* Any change to the clients props or the diagram comparison will set the cliet state again.
* Any change to the managers props or the diagram comparison , will change the managers
end note
: Render the diagram dom;
end
@enduml